import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeToggle } from "~/components/ThemeToggle";
import { ThemeInitializer } from "~/components/ThemeInitializer";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <style>{`
          /* Prevent flash of wrong theme */
          :root { color-scheme: light; }
          @media (prefers-color-scheme: dark) {
            :root { color-scheme: dark; }
            :root:not(.light) { color-scheme: dark; }
          }
          .dark { color-scheme: dark; }
          .light { color-scheme: light; }
        `}</style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-900 min-h-[100dvh] flex flex-col`}
      >
        <ThemeInitializer />
        <Providers>
          <main className="flex-1 flex flex-col">
            {children}
          </main>
        </Providers>
        <ThemeToggle />
      </body>
    </html>
  );
}
